#!/bin/bash

local DOTFILES_ROOT="$(realpath "${XDG_CONFIG_HOME}/../..")"
source "${DOTFILES_ROOT}/setup/utils.sh"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias c="clear"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -lah"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'

alias emacs="emacs -nw"
alias emacsw="emacs -w"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

if [ -n "$ZSH_VERSION" ]; then
    # For zsh
    # shellcheck source=/dev/null
    . "$(dirname "${(%):-%x}")/aliases.$(get_os_name)"
else
    # For bash
    # shellcheck source=/dev/null
    . "$(dirname "${BASH_SOURCE[0]}")/aliases.$(get_os_name)"
fi
